### PR TITLE
pipewire: Fix building EnumFormat spa object

### LINKED ISSUE #102: Broken EnumFormat object when format is without alpha
Possible issue at lines:
https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/screencast/pipewire_screencast.c#L178-L179
the size of the enum doesn't match the number of elements. But I don't know if it's valid API and thus a pipewire server/library bug.

`pw-cli` shows (notice truncated output):
```
  Object: size 96, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
    Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
      Id 2        (Spa:Enum:MediaType:video)
    Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
      Id 1        (Spa:Enum:MediaSubtype:raw)
    Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
      Choice: type Spa:Enum:Choice:Enum, flags 00000000 24 4
        Id 7        (Spa:Enum:VideoFormat:RGBx)
        Id 7        (Spa:Enum:VideoFormat:RGBx)
```

And the screencast doesn't work. This is with:
```
wlroots master
xdg-desktop-portal-wlr-0.2.0
pipewire-0.3.23
```

Previous discussion: https://github.com/swaywm/wlroots/issues/2784

### PR DESCRIPTION
**Pull request by st3r4g**
Make sure that in SPA_POD_CHOICE_ENUM_Id(n_vals, ...) we always pass
exactly n_vals arguments.
Fix #102

Tested on wlroots 0.12 (format with alpha) and wlroots master (format without alpha)

### CODE REVIEW

File: src/screencast/pipewire_screencast.c [hunk 1]
```diff
@@ -166,27 +166,32 @@ void xdpw_pwr_stream_init(struct xdpw_screencast_instance *cast) {
...
+	spa_pod_builder_add(&b, SPA_FORMAT_VIDEO_size,
+		SPA_POD_CHOICE_RANGE_Rectangle(
 			&SPA_RECTANGLE(cast->simple_frame.width, cast->simple_frame.height),
 			&SPA_RECTANGLE(1, 1),
 			&SPA_RECTANGLE(4096, 4096)),
-		// variable framerate
-		SPA_FORMAT_VIDEO_framerate, SPA_POD_Fraction(&SPA_FRACTION(0, 1)),
-		SPA_FORMAT_VIDEO_maxFramerate, SPA_POD_CHOICE_RANGE_Fraction(
+		0);
+	spa_pod_builder_add(&b, SPA_FORMAT_VIDEO_framerate, SPA_POD_Fraction(&SPA_FRACTION(0, 1)), 0);
```
Comment (emersion) [inline src/screencast/pipewire_screencast.c:187]: This adds a `0`. Is this something we were missing too?

Comment (emersion) [reply src/screencast/pipewire_screencast.c:187]: Oh, no, just an arg for `spa_pod_builder_add`.

Comment (st3r4g) [reply src/screencast/pipewire_screencast.c:187]: I simply expanded the `spa_pod_builder_add_object` macro that was been used before, so no difference. You can see the macro definition in `/usr/include/spa-0.2/spa/pod/builder.h`

File: src/screencast/pipewire_screencast.c [hunk 2]
```diff
@@ -166,27 +166,32 @@ void xdpw_pwr_stream_init(struct xdpw_screencast_instance *cast) {
 	enum spa_video_format format = xdpw_format_pw_from_wl_shm(cast);
 	enum spa_video_format format_without_alpha =
 		xdpw_format_pw_strip_alpha(format);
-	uint32_t n_formats = 1;
+
+	struct spa_pod_frame f;
+	spa_pod_builder_push_object(&b, &f, SPA_TYPE_OBJECT_Format, SPA_PARAM_EnumFormat);
+	spa_pod_builder_add(&b, SPA_FORMAT_mediaType, SPA_POD_Id(SPA_MEDIA_TYPE_video), 0);
```
Comment (emersion) [inline src/screencast/pipewire_screencast.c:172]: Would it make more sense to replace these trailing `0` with `NULL`?

Comment (st3r4g) [reply src/screencast/pipewire_screencast.c:172]: I've put `0` because that's what it is inside the macro that I expanded, but sure I can change it

Comment (st3r4g) [reply src/screencast/pipewire_screencast.c:172]: in the pipewire [docs](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/doc/spa/pod.md) they use `0` though

Comment (emersion) [reply src/screencast/pipewire_screencast.c]: Ah, actually you were correct, 0 is better. `spa_pod_builder_add` accepts an arbitrary number of `SPA_FORMAT_*` enum values, and zero ends the list. Since enum values are integers, 0 makes more sense.

Comment (st3r4g) [reply src/screencast/pipewire_screencast.c]: no problem

**Review by emersion — APPROVED** [review]
LGTM. Thanks for taking the time to dig up the correct way to do it.

**Comment by danshick** [comment]
I'll test this shortly and as long as it builds and runs fine we can merge.

Thanks for the fix!

**Review by danshick — APPROVED** [review]
Builds, installs, and runs fine. LGTM
